import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import AppProvider from "@/providers/AppProvider";
import "./globals.css";
import "./theme.css";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${outfit.variable} h-full antialiased`}
		>
			<body><AppProvider>{children}</AppProvider></body>
		</html>
	);
}
